# Generated by Django 4.1.5 on 2023-03-22 14:48

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coride', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=13, unique=True)),
                ('email', models.CharField(max_length=200, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('firstname', models.CharField(max_length=200)),
                ('lastname', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=13, unique=True)),
                ('email', models.CharField(max_length=200, unique=True)),
                ('password', models.CharField(max_length=30)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('car', models.CharField(max_length=200)),
                ('CarClass', models.CharField(max_length=30)),
                ('last_login', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('initial_address', models.CharField(max_length=200)),
                ('end_address', models.CharField(max_length=200)),
                ('length_time', models.TimeField()),
                ('length_metres', models.DecimalField(decimal_places=2, max_digits=10)),
                ('active', models.IntegerField()),
                ('client_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='coride.client')),
            ],
        ),
        migrations.CreateModel(
            name='EndOrders',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('end_address', models.CharField(max_length=200)),
                ('length_time', models.TimeField()),
                ('length_metres', models.DecimalField(decimal_places=2, max_digits=10)),
                ('route_ids', django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), size=None)),
                ('price', models.IntegerField()),
                ('date', models.DateTimeField(auto_now=True)),
                ('in_process', models.IntegerField()),
                ('driver_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='coride.driver')),
            ],
        ),
        migrations.AddField(
            model_name='client',
            name='company_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='coride.company'),
        ),
    ]
